apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample_apiserver
  labels:
    app: sample_apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample_apiserver
  template:
    metadata:
      labels:
        app: sample_apiserver
    spec:
      containers:
        - name: sample_apiserver
          image: REPLACE_IMAGE
          ports:
            - containerPort: 8081
