apiVersion: v1
kind: Service
metadata:
  name: sample_apiserver
  labels:
    app: sample_apiserver
spec:
  selector:
    app: sample_apiserver
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
